"""docs/DEMO_NUMBERS.md: the engine's numbers for the demo, written by `make demo` (SPEC §9: engine numbers live
here, never in the spec). Nothing in it is hand-edited."""
from __future__ import annotations

from app.core.money import format_inr


def _prob(p: float | None) -> str:
    if p is None:
        return "n/a"
    return "over 99%" if p >= 0.995 else "under 1%" if p < 0.005 else f"{p:.0%}"


def _top_bounce(p: dict) -> str:
    b = next((a for a in p["alerts"] if a["kind"] == "bounce_risk"), None)
    return f"{b['name']} {format_inr(b['amount_paise'])} on {b['due_date']}: {_prob(b['probability'])}" if b else "-"


def _rec_line(rec: dict) -> str:
    i = rec["impact"]
    if i["kind"] == "data":
        return (f"{rec['title']} (data: linked {i['accounts_linked_before']} → {i['accounts_linked_after']} of "
                f"{i['accounts_known']})")
    extra = []
    if rec["params"].get("cushion_paise") is not None:
        extra.append(f"cushion {format_inr(rec['params']['cushion_paise'])}")
    if rec["params"].get("binding"):
        extra.append(f"sized by {rec['params']['binding']}")
    return (f"{rec['title']} · 12-month score {i['score_12m_baseline']} → {i['score_12m_with_action']} "
            f"({i['score_delta_12m']:+d}) · {format_inr(i['annual_impact_paise'])} a year · EMI bounce risk "
            f"{_prob(i['bounce_risk_before'])} → {_prob(i['bounce_risk_after'])} · {rec['confidence']['label']}"
            + (f" · {', '.join(extra)}" if extra else ""))


def write(path, steps: list, others: dict, answers: list[tuple[str, str, object]], engine_version: str,
          seed: int) -> None:
    lines = [
        "# Demo numbers",
        "",
        f"Generated by `make demo` (engine {engine_version}, seed {seed}). These are engine outputs, written after the "
        "replay; nothing here is hand-edited, and the spec never quotes them (SPEC §9). The story they should tell is "
        "in `docs/DEMO.md`.",
        "",
        "## Persona A: T0 → +3",
        "",
        "| step | as of | score | change (behaviour / new data) | largest EMI bounce risk | dip before next income "
        "| confidence | reason codes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in steps:
        p = r.snapshot.payload
        fc, conf = p["forecast"], p["confidence"]
        d = r.diff.payload["score"] if r.diff else None
        change = f"{d['delta']:+d} ({d['behaviour']:+d} / {d['new_data']:+d})" if d else "-"
        dip = _prob(fc.get("dip_probability")) + (" (saturated)" if fc.get("dip_saturated") else "")
        codes = ", ".join(r.diff.reason_codes) if r.diff else "-"
        lines.append(f"| {r.step.name} | {r.step.as_of} | {p['score']['total']} {p['score']['band']} | {change} | "
                     f"{_top_bounce(p)} | {dip} | {conf['label']} ({conf['reason']}) | {codes} |")
    lines += ["", "### Recommendations at each step", ""]
    for r in steps:
        p = r.snapshot.payload
        lines.append(f"**{r.step.name}** ({r.step.label})")
        lines.append("")
        lines += [f"{rec['rank']}. {_rec_line(rec)}" for rec in p["recommendations"][:3]]
        for o in p.get("what_if_offers") or []:
            lines.append(f"- explore (a conditional prediction, never ranked): {o['title']}")
        down = next((rec["extra"].get("downside") for rec in p["recommendations"] if rec["type"] == "pay_down_card"),
                    None)
        if down and down.get("rebuild_to_paise"):
            lines.append(f"- clearing the card, downside: back to paying ~{down['pay_share']:.0%} and the balance "
                         f"rebuilds to about {format_inr(down['rebuild_to_paise'])} within "
                         f"{down['months_to_rebuild']} months")
        if r.diff:
            for c in r.diff.payload["rec_changes"]:
                lines.append(f"- {c['change']}: {c['title']} (caused by {', '.join(c['caused_by'])})")
        lines.append("")
    lines += ["## Personas B and C", "",
              "| persona | as of | score | income | dip before next income | largest EMI bounce risk | top recommendation |",
              "|---|---|---|---|---|---|---|"]
    for uid, snap in others.items():
        p = snap.payload
        top = _rec_line(p["recommendations"][0]) if p["recommendations"] else "none"
        lines.append(f"| {uid} | {snap.as_of} | {p['score']['total']} {p['score']['band']} | "
                     f"{p['metrics']['income_pattern']} | {_prob(p['forecast'].get('dip_probability'))} | "
                     f"{_top_bounce(p)} | {top} |")
    for provider, question, ans in answers:
        lines += ["", f"## The golden question ({provider})", "", f"> {question}", "",
                  f"Path `{ans.path}`" + (f", fell back: {ans.fallback_reason}" if ans.fallback_reason else "") +
                  f", {ans.latency_ms} ms.", ""]
        for st in ans.statements:
            lines.append(f"- **{st['label']}** {st['text']}")
            for ref in st["refs"]:
                src = ans.sources.get(ref)
                if src:
                    shown = "(in words)" if src["display"] == src["desc"] else src["display"]
                    lines.append(f"  - `{ref}` {shown}: {src['kind']}, {src['desc']}")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
