"""initial schema (SPEC §3). Snapshots are insert-only on Postgres (trigger below).

Revision ID: 0001
Revises: 
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('institution', sa.String(length=32), nullable=False),
    sa.Column('masked_number', sa.String(length=32), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('link_status', sa.String(length=16), nullable=False),
    sa.Column('known_via', sa.String(length=16), nullable=False),
    sa.Column('credit_limit_paise', sa.BigInteger(), nullable=True),
    sa.Column('min_balance_paise', sa.BigInteger(), nullable=True),
    sa.Column('apr_bps', sa.Integer(), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('loan_principal_paise', sa.BigInteger(), nullable=True),
    sa.Column('loan_outstanding_paise', sa.BigInteger(), nullable=True),
    sa.Column('loan_rate_bps', sa.Integer(), nullable=True),
    sa.Column('loan_tenure_months', sa.Integer(), nullable=True),
    sa.Column('loan_remaining_months', sa.Integer(), nullable=True),
    sa.Column('emi_paise', sa.BigInteger(), nullable=True),
    sa.Column('emi_next_due', sa.Date(), nullable=True),
    sa.Column('emi_day', sa.Integer(), nullable=True),
    sa.Column('lender_merchant_key', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'account_id')
    )
    op.create_table('ask_logs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ask_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=12), nullable=False),
    sa.Column('verdicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'ask_id')
    )
    op.create_table('balances',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'account_id', 'as_of_date')
    )
    op.create_table('consents',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('consent_id', sa.String(length=64), nullable=False),
    sa.Column('purpose_code', sa.String(length=16), nullable=False),
    sa.Column('purpose_text', sa.String(length=300), nullable=True),
    sa.Column('fi_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scope_accounts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data_from', sa.Date(), nullable=False),
    sa.Column('data_to', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'consent_id')
    )
    op.create_table('counterparties',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('pseudonym', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('match_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'pseudonym')
    )
    op.create_table('global_counters',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('raw_transactions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('raw_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=False),
    sa.Column('ingest_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('merchant_hint', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('balance_after_paise', sa.BigInteger(), nullable=True),
    sa.Column('channel_hint', sa.String(length=16), nullable=True),
    sa.Column('category_hint', sa.String(length=32), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'raw_id')
    )
    op.create_index('ix_raw_user_date', 'raw_transactions', ['user_id', 'txn_date'], unique=False)
    op.create_table('recurring_items',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'snapshot_id', 'item_id')
    )
    op.create_table('snapshot_diffs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('to_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('from_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('reason_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'to_snapshot_id')
    )
    op.create_table('snapshots',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'snapshot_id')
    )
    op.create_index('ix_snap_user_seq', 'snapshots', ['user_id', 'seq'], unique=True)
    op.create_table('transaction_sources',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('txn_id', sa.String(length=32), nullable=False),
    sa.Column('raw_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'txn_id', 'raw_id')
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('txn_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('narration_masked', sa.Text(), nullable=False),
    sa.Column('merchant_key', sa.String(length=80), nullable=False),
    sa.Column('merchant_name', sa.String(length=120), nullable=False),
    sa.Column('counterparty_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('category_source', sa.String(length=8), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=False),
    sa.Column('transfer_group_id', sa.String(length=32), nullable=True),
    sa.Column('is_bounce', sa.Boolean(), nullable=False),
    sa.Column('balance_after_paise', sa.BigInteger(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'txn_id')
    )
    op.create_index('ix_txn_user_account', 'transactions', ['user_id', 'account_id'], unique=False)
    op.create_index('ix_txn_user_date', 'transactions', ['user_id', 'txn_date'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('safety_floor_paise', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('validator_blocks',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ask_id', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('masked_candidate', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'ask_id', 'attempt')
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE OR REPLACE FUNCTION snapshots_immutable() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'snapshots are immutable (insert-only); erase via DELETE only';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER snapshots_no_update BEFORE UPDATE ON snapshots
            FOR EACH ROW EXECUTE FUNCTION snapshots_immutable();
        """)


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS snapshots_no_update ON snapshots")
        op.execute("DROP FUNCTION IF EXISTS snapshots_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validator_blocks')
    op.drop_table('users')
    op.drop_index('ix_txn_user_date', table_name='transactions')
    op.drop_index('ix_txn_user_account', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('transaction_sources')
    op.drop_index('ix_snap_user_seq', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('snapshot_diffs')
    op.drop_table('recurring_items')
    op.drop_index('ix_raw_user_date', table_name='raw_transactions')
    op.drop_table('raw_transactions')
    op.drop_table('global_counters')
    op.drop_table('counterparties')
    op.drop_table('consents')
    op.drop_table('balances')
    op.drop_table('ask_logs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
