"""account states, merchant rules, ingest watermark (SPEC D21, D22, D24)

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_states',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('ingest_seq', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'account_id', 'ingest_seq')
    )
    op.create_table('merchant_rules',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_key', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'merchant_key')
    )
    op.add_column('raw_transactions', sa.Column('ingest_seq', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_transactions', 'ingest_seq')
    op.drop_table('merchant_rules')
    op.drop_table('account_states')
    # ### end Alembic commands ###
