"""Train the ML fallback on synthetic narrations and evaluate on UNSEEN merchants (SPEC §5.4, D15)."""
from __future__ import annotations

from collections import Counter
from functools import lru_cache

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

from app.core.seeding import rng_for, seed_for
from app.pipeline.categorise import synth
from app.pipeline.categorise.model import MODEL_PATH, Categoriser, feature_text


def _xy(rows):
    feats = [feature_text(r["narration"], None, None, "credit_card" if r["channel"] == "card" else "savings")
             for r in rows]
    return [f[0] for f in feats], [r["amount_paise"] for r in rows], [f[1] for f in feats], [r["category"] for r in rows]


def _score(model: Categoriser, rows) -> dict:
    t, a, c, y = _xy(rows)
    pred, conf = model.predict(t, a, c)
    return {"n": len(rows), "accuracy": round(accuracy_score(y, pred), 4),
            "macro_f1": round(f1_score(y, pred, average="macro"), 4),
            "low_confidence_share": round(float(np.mean(np.asarray(conf) < 0.5)), 4)}


def train_and_evaluate(per_merchant: int = 2, holdout_share: float = 0.25) -> tuple[Categoriser, dict]:
    rng = rng_for("categoriser", "data")
    rows = synth.training_rows(rng, per_merchant=per_merchant)

    # Split 1: unseen merchants (group split by merchant name).
    merchants = sorted({r["merchant"] for r in rows})
    perm = rng_for("categoriser", "split").permutation(len(merchants))
    held = {merchants[i] for i in perm[: int(len(merchants) * holdout_share)]}
    train = [r for r in rows if r["merchant"] not in held]
    test = [r for r in rows if r["merchant"] in held]

    # Split 2 (harder): unseen merchant *types*: one suffix per category never seen in training.
    held_suffix = {cat: synth.SUFFIXES[cat][-1] for cat in synth.CLASSES}
    is_held_type = lambda r: r["merchant"].endswith(" " + held_suffix[r["category"]])
    train2 = [r for r in rows if not is_held_type(r)]
    test2 = [r for r in rows if is_held_type(r)]

    seed = seed_for("categoriser", "model")
    m1 = Categoriser(seed=seed).fit(*_xy(train))
    m2 = Categoriser(seed=seed).fit(*_xy(train2))
    metrics = {
        "rows": len(rows), "classes": synth.CLASSES,
        "class_counts": dict(sorted(Counter(r["category"] for r in rows).items())),
        "unseen_merchants": _score(m1, test),
        "unseen_merchant_types": {**_score(m2, test2), "held_out_suffixes": held_suffix},
        "caveat": "Synthetic template narrations: accuracy is optimistic versus real bank data (SPEC D15).",
    }
    final = Categoriser(seed=seed).fit(*_xy(rows))
    final.metrics = metrics
    return final, metrics


@lru_cache
def get_categoriser() -> Categoriser:
    """Load the trained artefact, training (deterministically) if it's missing."""
    if MODEL_PATH.exists():
        return Categoriser.load()
    model, _ = train_and_evaluate()
    model.save()
    return model


def write_report(metrics: dict, path) -> None:
    u, t = metrics["unseen_merchants"], metrics["unseen_merchant_types"]
    lines = [
        "# Categoriser evaluation",
        "",
        "Generated by `hisaab train-categoriser` (deterministic: same seed, same numbers). SPEC §5.4, D15.",
        "",
        "Rules categorise every merchant in `config/merchants.yaml`. The LightGBM fallback (char 2-5-gram TF-IDF",
        "on the payee + log amount + channel) handles the rest, mostly local merchants.",
        "",
        f"Training data: {metrics['rows']} synthetic narrations over {len(metrics['classes'])} classes "
        f"({', '.join(metrics['classes'])}).",
        "",
        "| Holdout | Rows | Accuracy | Macro-F1 | Share below 0.5 confidence (→ `other`) |",
        "|---|---|---|---|---|",
        f"| Unseen merchants (new names, familiar kind of shop, e.g. a new \"… Medical\") | {u['n']} | "
        f"{u['accuracy']:.1%} | {u['macro_f1']:.3f} | {u['low_confidence_share']:.1%} |",
        f"| Unseen merchant *types* (a category word never seen in training) | {t['n']} | "
        f"{t['accuracy']:.1%} | {t['macro_f1']:.3f} | {t['low_confidence_share']:.1%} |",
        "",
        "Held-out type words: " + ", ".join(f"{k}: \"{v}\"" for k, v in t["held_out_suffixes"].items()) + ".",
        "",
        f"**Caveat.** {metrics['caveat']} The first row mostly measures whether the model has learnt that",
        "\"Medical\" means health. The second row is the honest one for a merchant it has never seen the like of:",
        "those fall back to `other` or get a low-confidence guess, and the user can correct them",
        "(`category_source = user`).",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
