"""Train the ML fallback on synthetic narrations and evaluate on UNSEEN merchants (SPEC §5.4, D15)."""
from __future__ import annotations

from collections import Counter
from functools import lru_cache

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

from app.core.seeding import rng_for, seed_for
from app.pipeline.categorise import synth
from app.pipeline.categorise.model import MODEL_PATH, Categoriser, feature_text


def _xy(rows):
    feats = [feature_text(r["narration"], None, None, "credit_card" if r["channel"] == "card" else "savings")
             for r in rows]
    return [f[0] for f in feats], [r["amount_paise"] for r in rows], [f[1] for f in feats], [r["category"] for r in rows]


THRESHOLDS = (0.5, 0.6, 0.7, 0.8, 0.9)


def _score(model: Categoriser, rows) -> dict:
    t, a, c, y = _xy(rows)
    pred, conf = model.predict(t, a, c)
    conf_a, ok = np.asarray(conf), np.asarray(pred) == np.asarray(y)
    by_threshold = {}
    for th in THRESHOLDS:
        kept = conf_a >= th
        by_threshold[str(th)] = {"coverage": round(float(kept.mean()), 4),
                                 "precision": round(float(ok[kept].mean()), 4) if kept.any() else None}
    return {"n": len(rows), "accuracy": round(accuracy_score(y, pred), 4),
            "macro_f1": round(f1_score(y, pred, average="macro"), 4), "by_threshold": by_threshold}


def train_and_evaluate(per_merchant: int = 2, holdout_share: float = 0.25) -> tuple[Categoriser, dict]:
    rng = rng_for("categoriser", "data")
    rows = synth.training_rows(rng, per_merchant=per_merchant)

    # Split 1: unseen merchants (group split by merchant name).
    merchants = sorted({r["merchant"] for r in rows})
    perm = rng_for("categoriser", "split").permutation(len(merchants))
    held = {merchants[i] for i in perm[: int(len(merchants) * holdout_share)]}
    train = [r for r in rows if r["merchant"] not in held]
    test = [r for r in rows if r["merchant"] in held]

    # Split 2 (harder): unseen merchant *types*: one suffix per category never seen in training.
    held_suffix = {cat: synth.SUFFIXES[cat][-1] for cat in synth.CLASSES}
    is_held_type = lambda r: r["merchant"].endswith(" " + held_suffix[r["category"]])
    train2 = [r for r in rows if not is_held_type(r)]
    test2 = [r for r in rows if is_held_type(r)]

    seed = seed_for("categoriser", "model")
    m1 = Categoriser(seed=seed).fit(*_xy(train))
    m2 = Categoriser(seed=seed).fit(*_xy(train2))
    metrics = {
        "rows": len(rows), "classes": synth.CLASSES,
        "class_counts": dict(sorted(Counter(r["category"] for r in rows).items())),
        "unseen_merchants": _score(m1, test),
        "unseen_merchant_types": {**_score(m2, test2), "held_out_suffixes": held_suffix},
        "caveat": "Synthetic template narrations: accuracy is optimistic versus real bank data (SPEC D15).",
    }
    final = Categoriser(seed=seed).fit(*_xy(rows))
    final.metrics = metrics
    return final, metrics


@lru_cache
def get_categoriser() -> Categoriser:
    """Load the trained artefact, training (deterministically) if it's missing."""
    if MODEL_PATH.exists():
        return Categoriser.load()
    model, _ = train_and_evaluate()
    model.save()
    return model


def write_report(metrics: dict, path, threshold: float) -> None:
    """Only the unseen-merchant-TYPE holdout is reported (D21): synthetic names make "unseen merchant" trivially easy."""
    t = metrics["unseen_merchant_types"]
    rows = "\n".join(f"| {'**' + th + ' (configured)**' if float(th) == threshold else th} | {v['coverage']:.0%} | "
                     f"{v['precision']:.0%} |" for th, v in t["by_threshold"].items())
    lines = [
        "# Categoriser evaluation",
        "",
        "Generated by `hisaab train-categoriser` (deterministic: same seed, same numbers). SPEC §5.4, D15, D21.",
        "",
        "Rules categorise every merchant in `config/merchants.yaml` and user corrections become per-user merchant",
        "rules. The LightGBM fallback (char 2-5-gram TF-IDF on the payee + log amount + channel) handles the rest,",
        "mostly local merchants. Below `ml_min_confidence` the transaction is **Uncategorised**, which counts as",
        "essential spend so the emergency buffer is never overstated.",
        "",
        "## The number we report: merchant *types* the model has never seen",
        "",
        f"{t['n']} synthetic narrations whose category word never appears in training "
        f"(e.g. {', '.join(repr(v) for v in list(t['held_out_suffixes'].values())[:4])}).",
        f"Top-1 accuracy without a threshold: **{t['accuracy']:.0%}** (macro-F1 {t['macro_f1']:.2f}).",
        "",
        "| Confidence threshold | Share categorised | Precision of those |",
        "|---|---|---|",
        rows,
        "",
        "**Reading this.** The model's confidence is poorly calibrated on genuinely new kinds of merchant: even at",
        "0.9 only about half of its categorised guesses are right. The threshold therefore mainly controls how",
        "much we leave Uncategorised. The real fixes are labelled real-world narrations and user corrections.",
        "",
        "We deliberately do **not** quote accuracy on \"unseen merchants of a familiar type\" (a new \"… Medical\"):",
        "with template-generated names that number is near-perfect and meaningless (D21). "
        f"{metrics['caveat']}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
